# Generated by Django 4.2.1 on 2023-06-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_alter_servicio_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
