<<<<<<< HEAD
# Generated by Django 4.2.1 on 2023-06-19 20:32
=======
# Generated by Django 4.2.1 on 2023-06-20 02:30
>>>>>>> 4a937ba0fce8859f1c7d24931fa73f5047ab1509

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
<<<<<<< HEAD
            field=models.ImageField(upload_to='photos/'),
=======
            field=models.CharField(max_length=255),
>>>>>>> 4a937ba0fce8859f1c7d24931fa73f5047ab1509
        ),
    ]
